#!/bin/sh

set -e

    case "$1" in
      remove)
        rm /opt/pandora/base/Pandora-master.zip
        ;;
      abort-upgrade|abort-remove|abort-deconfigure|failed-upgrade|upgrade)
        ;;
      *)
        echo "Postrm called with unknown argument \`$1\`" >&2
        exit 1
        ;;
    esac

exit 0

